### ISSUE TITLE
CUDA error: an illegal memory access was encountered

### ISSUE THREAD

**Issue by qingtian1771** [rlworkgroup/garage#2077]
Hi,

I trained an example sac_half_cheetah_batch.py and test it using following simple code:

`from garage.experiment import Snapshotter
from garage import rollout

snapshotter = Snapshotter()
data = snapshotter.load('data/local/experiment/sac_half_cheetah_batch')
policy = data['algo'].policy

env = data['env']
for i_episode in range(5):
    env.reset()
    path = rollout(env, policy, animated=True)`

But I got some error as following:

/home/tq/anaconda3/envs/garage_env/bin/python /home/tq/PycharmProjects/garageTest/sac_half_cheetah_batch_test.py
2020-09-22 23:58:51.462424: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
/home/tq/anaconda3/envs/garage_env/lib/python3.6/site-packages/gym/logger.py:30: UserWarning: WARN: Box bound precision lowered by casting to float32
  warnings.warn(colorize('%s: %s'%('WARN', msg % args), 'yellow'))
/home/tq/anaconda3/envs/garage_env/lib/python3.6/site-packages/gym/logger.py:30: UserWarning: WARN: Box bound precision lowered by casting to float32
  warnings.warn(colorize('%s: %s'%('WARN', msg % args), 'yellow'))
Creating window glfw
Traceback (most recent call last):
  File "/home/tq/PycharmProjects/garageTest/sac_half_cheetah_batch_test.py", line 14, in <module>
    path = rollout(env, policy, animated=True)
  File "/home/tq/software/garage/src/garage/_functions.py", line 117, in rollout
    a, agent_info = agent.get_action(last_obs)
  File "/home/tq/software/garage/src/garage/torch/policies/stochastic_policy.py", line 39, in get_action
    action, agent_infos = self.get_actions(observation)
  File "/home/tq/software/garage/src/garage/torch/policies/stochastic_policy.py", line 82, in get_actions
    dist, info = self.forward(observations)
  File "/home/tq/software/garage/src/garage/torch/policies/tanh_gaussian_mlp_policy.py", line 103, in forward
    ret_mean = dist.mean.cpu()
RuntimeError: CUDA error: an illegal memory access was encountered

Process finished with exit code 1

I checked the code in tanh_gaussian_mlp_policy.py and found something related to cpu:
        ret_mean = dist.mean.cpu()

It seems when run the code on GPU, it will make some mistakes, I found there are some codes with .cpu() too, maybe it will cause the same problem.

How to resolve this problem, could you help? Thanks!

**Comment by avnishn** [comment]
Hi @qingtian1771 thanks for checking out Garage!

I wasn't able to replicate the bug that you encountered on your Garage installation.

Can you please also let us know the following:
1. Version of Cuda
2. Version of pytorch
3. Version of Garage, or the commit that you used, if you installed from our Github.

An issue that I found with your launch file, is that in order to use a GPU policy, you need to set the gpu mode of your python process to True. The snapshotter pickled your policy with the its tensors still on GPU, and you'd need to enable GPU mode in your launcher file in order to feed forward your pre-trained on-gpu SAC policy. I've modified the launcher file that you provided and it works for me when I open a pre-trained on-gpu SAC policy. 

```python
from garage.experiment import Snapshotter
from garage.sampler.utils import rollout
from garage.torch import set_gpu_mode # <------------- I've added this line

MAX_EPISODE_LENGTH = 1000  # you'll want to fill this in yourself,
                           # but for half-cheetah-v2, this is 1000
PATH_TO_SNAPSHOT_DIR = "SNAPSHOT_DIR"  # your snapshot dir.

set_gpu_mode(True, 0)  # <----------------------- I've added this line
snapshotter = Snapshotter()
data = snapshotter.load(PATH_TO_SNAPSHOT_DIR)
policy = data['algo'].policy
env = data['env']
for i_episode in range(5):
    env.reset()
    path = rollout(env,
                   policy,
                   max_episode_length=MAX_EPISODE_LENGTH,
                   animated=True)

```

This also could be an issue that me, @krzentner, and @lywong92 encountered when we were first adding GPU support to our torch branch earlier this year.
The problem ended up being that certain syntax would cause segmentation faults or illegal CUDA memory access errors when using older version of CUDA. It's tough to say without knowing your CUDA installation. 

For reference here is my information:
1. Version of Cuda: `10.2`
2. Version of pytorch: `1.5.1`
3. Version of Garage commit: `Master: f1b1852646e7600adf4fdd69c9b40360dcddac93`

Please try out the solution that I have listed for now, and let me know if you have any questions or if this didn't work out for you! I'd be more than happy to assist you.

Best,
@avnishn

**Comment by qingtian1771** [comment]
Hi @avnishn,
 
thanks for your help!
set_gpu_mode(True, 0) works all right, it solve the problem.

my information is here:
1. Cuda: 10.1
2. Python: 3.6.12
3. Garage version: I clone the code a few days ago, and install is locally, I don't know how to check version.

By the way, when I run the test code, harf cheetah run out of my screen, do you know how to fix it on the screen? 

Best regards,
@qingtian1771

**Comment by avnishn** [comment]
You can set your max path length in your eval script to be shorter that way it doesn't run off screen. But this is a problem handled by the mujoco py viewer written by open ai, that half cheetah is implemented using. 

You'll have to ask them. 

Thanks for getting back to me and letting me know it all worked out! 

Best,
Avnish
